# Generated by Django 4.2.4 on 2023-09-03 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="Nom")),
                ("slug", models.SlugField(blank=True)),
                ("image", models.ImageField(upload_to="images/categorie")),
            ],
            options={
                "verbose_name": "Categorie",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_ordered",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'achat"
                    ),
                ),
                ("complete", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Nouvelle", "Nouvelle"),
                            ("Valider", "Valider"),
                            ("Complete", "complete"),
                            ("Annuler", "Annuler"),
                        ],
                        default="Nouvelle",
                        max_length=10,
                    ),
                ),
                ("total", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Espece", "Espece"),
                            ("Mobile Money", "Mobile Money"),
                            ("Banque", "Banque"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Methode de Paiement",
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.customer",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Panier",
                "verbose_name_plural": "Panier",
            },
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Nom")),
                ("last_name", models.CharField(max_length=150, verbose_name="Prenom")),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(max_length=12, verbose_name="Contact"),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Mali", "Mali"),
                            ("Senegal", "Senegal"),
                            ("Cote d'Ivoire", "Cote d'Ivoire"),
                            ("Burkina Faso", "Burkina Faso"),
                        ],
                        default="Mali",
                        max_length=15,
                        verbose_name="Pays",
                    ),
                ),
                ("city", models.CharField(max_length=150, verbose_name="Ville")),
                ("street", models.CharField(max_length=50, verbose_name="Rue")),
                ("door", models.IntegerField(verbose_name="Porte")),
                (
                    "company_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la compagnie"
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.customer",
                        verbose_name="Client",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.order",
                        verbose_name="Panier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse de livraison",
                "verbose_name_plural": "Adresse de livraison",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nom")),
                ("description", models.CharField(max_length=1500)),
                (
                    "old_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ancien Prix"
                    ),
                ),
                ("new_price", models.PositiveIntegerField(verbose_name="Prix actuel")),
                ("slug", models.SlugField(blank=True)),
                ("image", models.ImageField(upload_to="products/images")),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'Ajout"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Populaire"
                    ),
                ),
                (
                    "is_new_arrivage",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Nouveau arrivage",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category_product",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Quantite"
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.order",
                        verbose_name="Panier",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.product",
                        verbose_name="Produits",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produits dans le Panier",
                "verbose_name_plural": "Produits dans le Panier",
            },
        ),
    ]
