# Generated by Django 4.2.4 on 2023-08-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.AlterField(
            model_name="customer",
            name="device",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
