# Generated by Django 4.2.4 on 2023-08-24 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_remove_customer_email_alter_customer_device"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.order",
                verbose_name="Panier",
            ),
            preserve_default=False,
        ),
    ]
