# Generated by Django 4.2.4 on 2023-08-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_remove_order_shipping_address_shippingaddress_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ip",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Adresse IP"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Espece", "Espece"),
                    ("Mobile Money", "Mobile Money"),
                    ("Banque", "Banque"),
                ],
                max_length=50,
                null=True,
                verbose_name="Methode de Paiement",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
